filebeat.inputs:
  - type: filestream
    id: siemx-test-auth
    enabled: true
    paths:
      - /var/log/siemx/*.log
    parsers:
      - multiline:
          type: pattern
          pattern: '^[A-Z][a-z]{2} '
          negate: true
          match: after

processors:
  - add_host_metadata: {}
  - add_fields:
      target: observer
      fields:
        type: siemx

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat
  keepfiles: 7
  permissions: 0644

http.enabled: true
http.host: 0.0.0.0
http.port: 5066
